# Generated by Django 5.0 on 2024-09-04 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dayhome_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayhomeChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayhome_provider.dayhomeprovider')),
            ],
            options={
                'db_table': 'dayhome_children',
            },
        ),
    ]
