# Generated by Django 5.0 on 2024-09-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayhome_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayhomeprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
